### PR TITLE
#27 Add 4 logos

### PR DESCRIPTION
**Pull request by DDCreationStudios**
Generated with: http://williamsharkey.com/Shapes.html

I like shapes 1,2,3 the most.
feel free to delete the other shapes and rename the remaining logo in an additional commit.

Let's go with one of them and we can change it all the time ;) 

@robeerob Can you also provide the resource of the page. Where did you find that? Is there somewhere a license?

### CODE REVIEW

**Comment by robeerob** [comment]
@DDCreationStudios Awesome! Your suggestions look good, and I added another one that I generated. The idea behind the shape I chose is that a pyramid/triangle shape can symbolize the rising part of our name, and the shape might resemble the path up a mountain.

**Comment by DDCreationStudios** [comment]
@robeerob What would you like to do? Shall we add all 5 to the repo? Or should set up a poll for the community? I would vote for shape(2).html

**Comment by robeerob** [comment]
@DDCreationStudios Maybe add all 5, and then the community can help us decide at the next meetup?

**Comment by DDCreationStudios** [comment]
@robeerob Great idea! Let's do it that way! :)

**Pull request merged**
