### PR TITLE
Create Code of Conduct

### LINKED ISSUE #13: Create a code of conduct

### PR DESCRIPTION
**Pull request by robeerob**
Closes #13.

### CODE REVIEW

**Comment by DDCreationStudios** [comment]
@robeerob  Thanks! I will adapt it a little. Going more in the direction we had for FCCVienna. I think you haven't been at the meetup where we elaborated the Code of Conduct, but we have chosen and adapted a good one. (https://github.com/FCCVienna/FCCVienna/blob/master/CodeOfConduct.md)
On a sidenote:  We shouldnt have a license statement like that in the code of conduct. Not only is this license not suitable, but we should also refer to our license file and not create a second license ;)

**Comment by robeerob** [comment]
Great. I agree with your feedback, and thanks for offering to change things tomorrow. The license was meant to be for that document only, but if that is not clear it's not a good license anyways ;)

**Comment by robeerob** [comment]
..and yes, I was not there at the "code of conduct" meetup. Just saw we had a contributing.md, but somehow didn't notice the CodeOfConduct.md.

**Comment by DDCreationStudios** [comment]
@robeerob basically copied everything from FCCVienna
More detailled adaptions can be made over the next months. 

Feel free to merge if you are ok with it :)

**Pull request merged**
